// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5hMnaodWHTXFAxM56X3aDF1qHPGlBZ_Q',
    appId: '1:437537205054:web:935508aae007c9901e9a6f',
    messagingSenderId: '437537205054',
    projectId: 'rentatouille-768fd',
    authDomain: 'rentatouille-768fd.firebaseapp.com',
    storageBucket: 'rentatouille-768fd.appspot.com',
    measurementId: 'G-T43H14RBQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU4jf1UQi_xey7vuKvVNtju4L5jGFmj6w',
    appId: '1:437537205054:android:cc4ab21df43fd3271e9a6f',
    messagingSenderId: '437537205054',
    projectId: 'rentatouille-768fd',
    storageBucket: 'rentatouille-768fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyLtCjsao3kR3H_vCaE-MsLv-WWHGhLKo',
    appId: '1:437537205054:ios:0fac995df24ded761e9a6f',
    messagingSenderId: '437537205054',
    projectId: 'rentatouille-768fd',
    storageBucket: 'rentatouille-768fd.appspot.com',
    iosClientId: '437537205054-k7m829nufo1cn54r19d821ae88122q7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentatouille',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyLtCjsao3kR3H_vCaE-MsLv-WWHGhLKo',
    appId: '1:437537205054:ios:f2f16e9e465fae051e9a6f',
    messagingSenderId: '437537205054',
    projectId: 'rentatouille-768fd',
    storageBucket: 'rentatouille-768fd.appspot.com',
    iosClientId: '437537205054-6bfv14v52vf4buqaprvsa0n998c0bc94.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentatouille.RunnerTests',
  );
}
